### ISSUE TITLE
Testing with TranzactIO

### ISSUE THREAD

**Issue by RobinJDCox** [gaelrenoux/tranzactio#17]
TranzactIO looks really interesting library, great work! 🙂  I'm looking at solving exactly the kind of problem you've described where I can complete my transaction after performing multiple DB operations and various bits if business logic.

My question is around testing, is there a recommended approach when using TranzactIO? If my database classes return a `RIO[Connection, A]` and my core service logic completes that transaction, resulting in a `RIO[Database, A]` it would be great to be able to provide implementations of `Connection` and `Database` that don't require a running SQL database.

**Comment by PawelJ-PL** [comment]
I'm using TranzactIO in my project. For tests I've prepared fake connection source layer like: https://github.com/PawelJ-PL/elevation_of_privilege_online/blob/master/src/test/scala/com/github/paweljpl/eoponline/testdoubles/FakeConnectionSource.scala. Thanks to I'm able to use it in my tests, for example https://github.com/PawelJ-PL/elevation_of_privilege_online/blob/be161a6fe6873e9cd117b22a7af7567fe5a0e426/src/test/scala/com/github/paweljpl/eoponline/game/GamesSpec.scala#L53. Of course, I don't know if this is the recommended approach, if there are any others, I'd be happy to see them.

**Comment by RobinJDCox** [comment]
That works for my use-case, thanks for the suggestion!

**Comment by gaelrenoux** [comment]
I haven't missed that and I think it's a great idea, I just don't have had the time yet. I thought I could work on it today, but issue 18 took priority.

**Comment by gaelrenoux** [comment]
Solved in #22
