### ISSUE TITLE
Lack of support for doobie streams

### ISSUE THREAD

**Issue by jgiunti-coatue** [gaelrenoux/tranzactio#20]
Noticed this when trying to work with fs2.Streams returned by doobie.

Previously my code had something like this on order to try and convert an fs2.Stream[ConnectionIO, T]] into a ZStream
```
fragment
  .queryWithLogHandler[T](lh)
  .streamWithChunkSize(512)
  .translate(new (Query ~> TZIO) { def apply[A](a: Query[A]): TZIO[A] = tzio(a) })
  .toZStream(512)
  .mapError(DbException.Wrapped)
```
But what I found at runtime is that the stream was executing in internal streaming mode vs final streaming (it is trying to load the entire result into memory before it begins processing the stream).

If you check out the doobie docs, in order to get final streaming one must call the transactor on the stream itself before it is compiled. Looking at doobie.syntax.StreamOps we see that a different transformation is called: `xa.transP.apply(fa)`

I created this helper in my code that should resolve this.
```
final def tzioS[A](q: fs2.Stream[Query, A]): ZStream[Connection, DbException, T] =
    ZStream.accessStream[Connection] { c =>
      c.get.transP(zio.interop.catz.monadErrorInstance).apply(q).toZStream(512)
    }.mapError(DbException.Wrapped)
```

Is this something we might consider adding to this project? Do you see any other reason why final streaming may not be working properly?

**Comment by gaelrenoux** [comment]
Thanks for the report and the code idea ! I ported it pretty much identically into the repo.

**Comment by jgiunti-coatue** [comment]
@gaelrenoux awesome, thanks!

**Comment by fpatin** [comment]
Hi @gaelrenoux ,

When do you plan to release the project with this new feature?

thanks

**Comment by gaelrenoux** [comment]
The end of the year has been pretty busy, I didn't have time for tranzactio. I'll ship a release in the beginning of January.

**Comment by gaelrenoux** [comment]
Two days too late to still count as the beginning of January, but it's done :-)
