### ISSUE TITLE
May be we can deprecate this repository

### ISSUE THREAD

**Issue by kuzkdmy** [gaelrenoux/tranzactio#30]
I also use this repo
But was unable with upgrade to codebase working with cats-effect 3
And finally I just did a small change and all library does not make sense to be used in my project
Very little amount of code is required

```
import doobie.Transactor
import doobie.implicits._
import zio.interop.catz._
import zio.{Has, Task, ZIO}

package object repository {
  type TranzactIO[T] = ZIO[Has[Transactor[Task]], Throwable, T]

  def tzio[T](c: doobie.ConnectionIO[T]): TranzactIO[T] = {
    for {
      tx <- ZIO.service[Transactor[Task]]
      res <- c.transact(tx)
               .foldM(
                 e => Task.fail(e),
                 r => Task.succeed(r)
               )
    } yield res
  }
}
```

**Comment by gaelrenoux** [comment]
I have a [PR opened for Doobie 1.0 and Cats-Effect 3](https://github.com/gaelrenoux/tranzactio/pull/31). I'm waiting for some comments, but I'll merge it in quickly and publish a milestone (I won't publish a full release until Doobie does it).

Regarding your code: unless I am mistaken, you won't have a way to run all queries that you compose together through ZIO in a single transaction. Your conversion from ConnectionIO to ZIO provides the bounds of the transaction. If you have two instances of your TranzactIO[T], when you combine them and run the code, each instance will be run in its own transaction. Therefore, if you want to combine stuff within the same transaction, you still have to use ConnectionIO.

If this is OK for you, then absolutely you don't need TranzactIO.
