### ISSUE TITLE
Scala 3 artefacts?

### ISSUE THREAD

**Issue by rbmdotdev** [gaelrenoux/tranzactio#33]
Is there a reason why this is not published for Scala3?

any chance it could be?

**Comment by heaven-born** [comment]
It looks like Scala 3 breaks some important convention that allows replacing environment parameter when we "run" transaction, so I guess this was the reason. Here is the issue: https://github.com/lampepfl/dotty/issues/12077

In ZIO 2.0.0-M6 there is no `Has` anymore, so it will be possible to do the same type of trick in Scala 3 now.

**Comment by gaelrenoux** [comment]
I'm just starting to play around with Scala 3. Also, I haven't been using ZIO for a while, so I haven't followed the latest changes. While I'll definitely get around to upgrading tranzactio to Scala 3 and ZIO 2, I can't make any promises as to when that will happen.
