### ISSUE TITLE
Adds Doobie Stream handling to the README

### ISSUE THREAD

**Issue by ghost** [gaelrenoux/tranzactio#35]
Doobie has support for transacting a fs2 stream. For ex: I can convert a `Stream[ConnectionIO, A]` into a `Stream[IO, A]` ( see [doobie-final-streaming][1] )

Does tranzactio provide similar functionality? If not, how would you simulate this?

[1]: https://tpolecat.github.io/doobie/docs/04-Selecting.html#final-streaming

**Comment by gaelrenoux** [comment]
Yes, tranzactio has a feature for this. In the Doobie package, you have a `tzioStream` method, which takes a `fs2.Stream[ConnectionIO, A]` and returns a `zio.stream.ZStream[Connection, DbException, A]`.

I'll add this to the README.

**Comment by rrampr** [comment]
Oh I knew about `tzioStream`. The biggest thing I wanted to know was how to transform a `ZStream[Connection DbException, A]` into a `ZStream[Database, DbException, A]`. Currently, the transaction methods say for ex:`Database#transactionOrDieR` only operate on zio effects and not zio streams. 

Whereas in Doobie (w/ using `toZStream()` from `zio-interop-cats), you are able to transform `Stream[ConnectionIO, A]` into something like this`ZStream[DoobieTransactorLayerProvider, Throwable, A]`

**Comment by gaelrenoux** [comment]
Ah OK, I get your point. Unfortunately, I'm not too familiar with ZIO streams, and in the sample streaming application I converted the stream to a ZIO before applying the Database. I'll try to take a look at this, but I welcome any PR on the subject.
