### ISSUE TITLE
Add support of multiple databases

### ISSUE THREAD

**Issue by heaven-born** [gaelrenoux/tranzactio#51]
I worked with the tranzactio a long time ago, and I remember an issue I could not overcome: I had more than one database and I wanted to combine two ZIOs that required two connections to two different databases and then do `transactionOrDie` for each of the connection separately. This is just a prototype, but I wanted something like this:

```

type ConnectionOne = Connection[DatabaseOne]
type ConnectionTwo = Connection[DatabaseTwo]

val list: ZIO[ConnectionOne, DbException, List[String]] = tzio {
  sql"SELECT name FROM users".query[String].to[List]
}

val list2: ZIO[ConnectionTwo, DbException, List[String]] = tzio {
  sql"SELECT name FROM users".query[String].to[List]
}

val combined:ZIO[ConnectionOne && ConnectionTwo, DbException, List[String]] = list *> list2

val foo: ZIO[DatabaseOne && DatabaseTwo, String, Long] = Database.transactionOrDie(combined)


```

I don't think something like this is doable in scala 2.13, but maybe in scala 3 is possible.

**Comment by guersam** [comment]
It's possible using [Subtypes in ZIO Prelude](https://zio.github.io/zio-prelude/docs/newtypes/#subtypes) in Scala 2.13, but not yet in Scala 3 due to 
 a compiler issue or something AFAIK.

**Comment by gaelrenoux** [comment]
I can definitely see how such a feature would be useful.

A simple way to make it easier would be for Tranzactio to provide directly  a `DatabaseWrapper` that inherits `Database` (equivalent to your `DatabaseOne`). Then you could declare your own subclasses, where you would only need to extend the wrapper without having to override anything.

I could also provide a `DatabaseTyped[A]`, with an arbitrary type-parameter that would work as a marker. It would also inherit the wrapper, and you would only need to provide a marker type. Not sure if that's better than just having you declare a subclass of `DatabaseWrapper` directly.

**Comment by gaelrenoux** [comment]
I have a PR for this use case. What do you think? I'm not fan of the name `DatabaseT` for the typed database, but couldn't find a better idea. `DatabaseCustom` isn't great, it's not especially custom. `MyDatabase` maybe?
